// <auto-generated />
using System;
using MagicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagicVilla_VillaAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240624203917_FiveUser")]
    partial class FiveUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.LocalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Pool, Wi-Fi, BBQ",
                            CreatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1105),
                            Details = "Beautiful villa with sea view.",
                            ImageUrl = "https://example.com/villa1.jpg",
                            Name = "Villa Sunshine",
                            Occupancy = 8,
                            Rate = 350.0,
                            Sqft = 2500,
                            UpdatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1125)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Fireplace, Hot Tub",
                            CreatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1130),
                            Details = "Cozy retreat in the mountains.",
                            ImageUrl = "https://example.com/villa2.jpg",
                            Name = "Mountain Retreat",
                            Occupancy = 6,
                            Rate = 200.0,
                            Sqft = 1500,
                            UpdatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1132)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "Gym, Wi-Fi",
                            CreatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1136),
                            Details = "Modern villa in the city center.",
                            ImageUrl = "https://example.com/villa3.jpg",
                            Name = "Urban Oasis",
                            Occupancy = 4,
                            Rate = 300.0,
                            Sqft = 1800,
                            UpdatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1137)
                        },
                        new
                        {
                            Id = 4,
                            Amenity = "Pool, Private Beach",
                            CreatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1140),
                            Details = "Luxury villa right on the beach.",
                            ImageUrl = "https://example.com/villa4.jpg",
                            Name = "Beachfront Paradise",
                            Occupancy = 10,
                            Rate = 500.0,
                            Sqft = 3000,
                            UpdatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1141)
                        },
                        new
                        {
                            Id = 5,
                            Amenity = "Garden, Wi-Fi",
                            CreatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1144),
                            Details = "Charming villa in the countryside.",
                            ImageUrl = "https://example.com/villa5.jpg",
                            Name = "Countryside Escape",
                            Occupancy = 5,
                            Rate = 250.0,
                            Sqft = 2200,
                            UpdatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1145)
                        },
                        new
                        {
                            Id = 6,
                            Amenity = "Pool, Outdoor Shower",
                            CreatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1147),
                            Details = "Quiet villa in the desert.",
                            ImageUrl = "https://example.com/villa6.jpg",
                            Name = "Desert Hideaway",
                            Occupancy = 4,
                            Rate = 280.0,
                            Sqft = 1600,
                            UpdatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1148)
                        },
                        new
                        {
                            Id = 7,
                            Amenity = "Canoe, Fireplace",
                            CreatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1151),
                            Details = "Relaxing villa by the lake.",
                            ImageUrl = "https://example.com/villa7.jpg",
                            Name = "Lakeside Cottage",
                            Occupancy = 6,
                            Rate = 220.0,
                            Sqft = 2000,
                            UpdatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1152)
                        },
                        new
                        {
                            Id = 8,
                            Amenity = "Pool, Hammocks",
                            CreatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1155),
                            Details = "Exotic villa in a tropical setting.",
                            ImageUrl = "https://example.com/villa8.jpg",
                            Name = "Tropical Getaway",
                            Occupancy = 8,
                            Rate = 400.0,
                            Sqft = 2700,
                            UpdatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1156)
                        },
                        new
                        {
                            Id = 9,
                            Amenity = "Ski Storage, Hot Tub",
                            CreatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1158),
                            Details = "Comfortable villa near the ski slopes.",
                            ImageUrl = "https://example.com/villa9.jpg",
                            Name = "Ski Chalet",
                            Occupancy = 5,
                            Rate = 310.0,
                            Sqft = 1400,
                            UpdatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1159)
                        },
                        new
                        {
                            Id = 10,
                            Amenity = "Hiking Trails, Wi-Fi",
                            CreatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1162),
                            Details = "Peaceful villa in the forest.",
                            ImageUrl = "https://example.com/villa10.jpg",
                            Name = "Forest Retreat",
                            Occupancy = 6,
                            Rate = 270.0,
                            Sqft = 1900,
                            UpdatedDate = new DateTime(2024, 6, 25, 9, 39, 13, 264, DateTimeKind.Local).AddTicks(1163)
                        });
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("VillaNo");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MagicVilla_VillaAPI.Models.VillaNumber", b =>
                {
                    b.HasOne("MagicVilla_VillaAPI.Models.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MagicVilla_VillaAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MagicVilla_VillaAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagicVilla_VillaAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MagicVilla_VillaAPI.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
